### PR TITLE
Add documentation for no_magic and no_inline relation qualifiers

### PR DESCRIPTION
**Pull request by sharon-wang**
Adds documentation for
* relation qualifiers: `no_magic` and `no_inline`
* options: `inline-exclude` and `magic-transform-exclude`

These relation qualifiers and options were introduced in https://github.com/souffle-lang/souffle/pull/2000 (pending review/merge).

### CODE REVIEW

**Comment by sharon-wang** [comment]
FYI: @OlivierHamel

**Review by b-scholz — COMMENTED** [review]
Please can you add the qualifiers here as well:
https://souffle-lang.github.io/relations

Also, please update the rail-road diagrams. Copy the ebbing text into the grammar box, produce the xhtml and copy the svg into the img directory for relation_decl.svg.

**Comment by sharon-wang** [comment]
Added `no_magic` and `no_inline` to the diagram. Preview: 

image


(https://github.com/sharon-wang/souffle-lang.github.io/blob/no_magic_no_inline/img/relation_decl.svg)

**Review by b-scholz — APPROVED** [review]

**Comment by b-scholz** [comment]
Thanks for the contribution!

Please can you also add the flags to this page:
https://souffle-lang.github.io/execute

**Pull request merged**
