### PR TITLE
Update C++ interface docs

### PR DESCRIPTION
**Pull request by doctorn**
Currently [the hosted version of the C++ interface documentation](https://souffle-lang.github.io/interface#why-do-we-need-c-interface) is unreadable due to formatting issues. This PR fixes the formatting and updates the example to be more concise.

### CODE REVIEW

**Comment by doctorn** [comment]
I think a similar fix wants to be applied to the page on SWIG at some point as well.

**Comment by doctorn** [comment]
Thanks for the comment - yeah definitely! I’ll have a look at some point this weekend.

**Comment by doctorn** [comment]
@b-scholz I hope this is closer to what you were thinking

**Comment by b-scholz** [comment]
Thanks for the effort!

**Pull request merged**
